version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: recommender_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_pass
    volumes:
      - redis_data:/data

volumes:
  redis_data: 