version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: recommender_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: recommender_user
      MONGO_INITDB_ROOT_PASSWORD: recommender_pass
      MONGO_INITDB_DATABASE: recommender
    volumes:
      - mongodb_data:/data/db
      - ../mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongodb_data: 